### ISSUE TITLE
Am I installing this correctly?

### ISSUE THREAD

**Issue by Nate-GIS** [openone/litero#2]
I'm on a Windows 10 Laptop. I installed Node.js, then i opened that script in cmd, then entered "npm install -g litero" (without the quotes), and i receive multiple lines of errors. I even tried running the script with admin privileges, still the same result.

**Comment by openone** [comment]
Hi there!

May I bother u for a screenshot of error plz ?

**Comment by Nate-GIS** [comment]
I got it working, had to reboot my pc. Also, the code is slightly different than inside your wiki
